### 1. Tüm kitapları getir
GET http://localhost:3000/books

### 2. ID'ye göre kitap getir
GET http://localhost:3000/books/1

### 3. Yeni kitap ekle
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Test book post",
  "author": "Test author",
  "rating": 3
}

### 4. Kitap güncelle
PATCH http://localhost:3000/books/1
Content-Type: application/json

{
  "title": "Book 1 Updated",
  "author": "Author 1 Updated",
  "rating": 3
}

### 5. Kitap sil
DELETE http://localhost:3000/books/1